version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: inventory_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      timeout: 5s
      retries: 10

  airflow-init:
    image: apache/airflow:2.8.1
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/inventory_db
      AIRFLOW__CORE__FERNET_KEY: "xMnjO6Tf6kMLpQwIgcuaDIsLfwAxxoShHUM_Gs0KpHo="
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
     - ./dags:/opt/airflow/dags
     - ./logs:/opt/airflow/logs
     - ./data:/opt/airflow/data
     - ./requirements.txt:/requirements.txt
    command: >
     bash -c "
       pip install --user -r /requirements.txt &&
       echo 'Starting Airflow initialization...' &&
       airflow db init &&
       airflow users create \
       --username admin \
       --firstname Admin \
       --lastname User \
       --role Admin \
       --email admin@example.com \
       --password admin &&
       echo 'Airflow ready!'
          "

    restart: on-failure

  airflow-webserver:
    image: apache/airflow:2.8.1
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/inventory_db
      AIRFLOW__CORE__FERNET_KEY: "xMnjO6Tf6kMLpQwIgcuaDIsLfwAxxoShHUM_Gs0KpHo="
    ports:
      - "8081:8080"
    volumes:
     - ./dags:/opt/airflow/dags
     - ./logs:/opt/airflow/logs
     - ./data:/opt/airflow/data
     - ./requirements.txt:/requirements.txt
    command: >
     bash -c "
     pip install --user -r /requirements.txt &&
     airflow webserver
      "
    restart: always

  airflow-scheduler:
    image: apache/airflow:2.8.1
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/inventory_db
      AIRFLOW__CORE__FERNET_KEY: "xMnjO6Tf6kMLpQwIgcuaDIsLfwAxxoShHUM_Gs0KpHo="
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
      - ./requirements.txt:/requirements.txt
    command: >
       bash -c "
       pip install --user -r /requirements.txt &&
       airflow scheduler
        "

    restart: always

volumes:
  postgres_data:
